---
title: "Workshop 3"
author: "Ann Thomas"
date: "2025-04-09"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
#install.packages("tidyverse")
library(tidyverse)
# install.packages("janitor")
library(janitor)
```

```{r}
# Import CSV and set proper headers
shark_program <- read_csv("../data/qfish.csv") |>
  row_to_names(row_number = 2, remove_rows_above = FALSE) |> 
  clean_names()

head(shark_program)
```
```{r}
# SHARK
shark_catch <- shark_program |>
  select(area | contains("shark")) |>
  row_to_names(row_number = 1) |>
  rename(Area = 1) |>
  mutate(across(-Area, as.numeric))

# TURTLE
turtle_catch <- shark_program |>
  select(area | contains("turtle")) |>
  row_to_names(row_number = 1) |>
  rename(Area = 1) |>
  mutate(across(-Area, as.numeric))
```
# Pivot wide tibbles longer
```{r}
# Pivot to long format
shark_catch_long <- shark_catch |>
  pivot_longer(!Area, names_to = "Year", values_to = "Nos")

turtle_catch_long <- turtle_catch |>
  pivot_longer(!Area, names_to = "Year", values_to = "Nos")
```
# Make stats tibbles
```{r}
# SHARK stats
shark_stats <- shark_catch_long |>
  filter(Area != "Grand Total") |>
  group_by(Year) |>
  summarise(
    Mean = mean(Nos, na.rm = TRUE),
    SD = sd(Nos, na.rm = TRUE)
  ) |>
  mutate(
    Year = as.numeric(Year),
    Taxa = "Sharks"
  )

# TURTLE stats
turtle_stats <- turtle_catch_long |>
  filter(Area != "Grand Total") |>
  group_by(Year) |>
  summarise(
    Mean = mean(Nos, na.rm = TRUE),
    SD = sd(Nos, na.rm = TRUE)
  ) |>
  mutate(
    Year = as.numeric(Year),
    Taxa = "Turtles"
  )

# Combine stats
combine_stats <- bind_rows(shark_stats, turtle_stats)

```

```{r}
ggplot(combine_stats, aes(x = Year, y = Mean, color = Taxa)) +
  geom_line(linewidth = 1) +
  geom_point(size = 2) +
  geom_errorbar(aes(ymin = Mean - SD, ymax = Mean + SD), width = 0.2) +
  labs(
    title = "Mean Marine Species Catches per Year (2001–2025)",
    x = "Year",
    y = "Mean Number Caught",
    color = "Species Group"
  ) +
  theme_minimal()

```

```{r}
ggsave( "../output/marine_species_catch_plot.png",  # Name of the output file
  width = 10,                                  # Width in inches
  height = 6,                                  # Height in inches
  dpi = 300                                    # High resolution (good for print)
)
```

















